### PR TITLE
Issue 1: Add Introduction summary

### PR DESCRIPTION
**Pull request by nengard**

### CODE REVIEW

**Comment by adahms** [comment]
@nengard - Thank you for the pull request!

The text added looks good as an introduction for members of CCS, but I wonder if we should have a different one, or perhaps some added wording aimed more at members of the community.

This could be a good location to use a conditional and have separate introductions for an upstream and downstream version of the guide.

What do you think?

**Comment by nengard** [comment]
I think I can rewrite it to be helpful to anyone and not have to bother with conditionals. I'll take another stab at it :)

**Comment by nengard** [comment]
What do you think now?  I also think we need to update the overview now because it talks about CCS.

**Comment by adahms** [comment]
@nengard - Thank you for the update!

I like the new wording, but I still wonder if we might need to be a bit more specific for our separate audiences. There will be both an upstream and downstream version of the guide, so perhaps something for downstream teams that lets them know this is our recommended framework for working with communities along the lines you have here, and perhaps something for upstream communities that lets them know that Red Hat has provided some guidelines on how they can hook up their community documentation.

What do you think? I'm sorry for all the comments, but the introduction will set the tone for the rest of the guide, so I'm just rolling around some thoughts.

**Comment by nengard** [comment]
@adahms what about expanding on this and just saying 

> This guide is geared at helping teams in enterprise organizations collaborate with upstream communities on documentation.  

> For the enterprise organizations, this guide will provide tips for evaluating a community to see if they are prepared for collaboration with an enterprise software team, communication guidelines, information on supported and unsupported tools, and guidelines for structuring your repository.

> For the communities, this guide will provide .....

**Comment by adahms** [comment]
@nengard - Sounds good! In this case, I think it would be alright to mention Red Hat specific instead of enterprise organizations in general given the use case for the document, and should we need to expand that use case in the future, we can always create a new 'brand' directory that uses its own introduction to cover that. :)

**Comment by nengard** [comment]
Updated pull request here: https://github.com/redhat-documentation/community-contribution-template/pull/30

**Pull request closed without merging**
